/*"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
http://projecteuler.net/problem=2
*/

#include <stdio.h>
long fibonacci(int);

int main()
{
	int i = 0;
	long temp = 0;
	long store = 0;
	while(temp <= 4000000)
	{
		if(temp%2==0)
		{
			store += temp;
		}
		temp = fibonacci(i);
		i++;
	}
	printf("%d\n", store);
	return 0;
}

long fibonacci(int step)
{
	if((step == 0) || (step == 1))
		{
		return step;
		}
	else
		return (fibonacci(step-1) + fibonacci(step-2));
}